### ISSUE TITLE
회원 가입 시 각 필드에 제약사항을 적용한다.

### ISSUE THREAD

**Issue by gusah009** [Busan-Dinosaur/FoodBowl-Server#50]
## 📝 Description

회원 가입 시 각 필드에 제약사항을 적용한다.

## 🎱 Todo

- [x] 아이디 중복체크를 수행한다.
- [x] 닉네임 중복체크를 수행한다.
- [x] 아이디 제약사항 : 4~12자 영어, 숫자, '_' 만 가능합니다.
- [x] 비밀번호 제약사항 : 8~20자 영문과 숫자를 사용하세요.
- [x] 닉네임 제약사항 : 1~16자 한글, 영어, 숫자만 가능합니다.
